### ISSUE TITLE
[Icon request] Add new social Icons

### ISSUE THREAD

**Issue by psynyde** [cyberalien/line-md#1]
I really like the icons but its lacking some major social site's icons. Here's a list of icons that i want to use but not available:
- Reddit
- instagram
- telegram
- buy me a coffee (or just a coffee logo)

also addition of 
- sun
- moon
- lightbulb
- article icon

these would be nice to have

**Comment by cyberalien** [comment]
Good ideas. Thanks.

It might take a while, mostly because social icons require re-designing icon piece by piece then figuring out how to better animate it.

Reddit icons:
- https://raw.githubusercontent.com/cyberalien/line-md/dev/svg/Social/reddit.svg
- https://raw.githubusercontent.com/cyberalien/line-md/dev/svg/Social/reddit-circle.svg

edit: 2 more:
- https://raw.githubusercontent.com/cyberalien/line-md/dev/svg/Social/reddit-loop.svg
- https://raw.githubusercontent.com/cyberalien/line-md/dev/svg/Social/reddit-circle-loop.svg

**Comment by cyberalien** [comment]
So it appears linking icons here doesn't work well. When browsing in dark mode, it shows as black icon on black background because `currentColor` defaults to black when used as background image, which is what GitHub markdown uses.

Reddit icons done. In addition to 2 icons listed above, added infinite loop. See demo here: https://twitter.com/slava_trushkin/status/1536022909835149314

I think other icons should be easier to animate.

**Comment by cyberalien** [comment]
Telegram and Instagram icons are done:
![icons-1655137697659](https://user-images.githubusercontent.com/822287/173401568-d9595816-26af-4814-80e0-159b2babc487.gif)

Buy me a coffee icon won't work because logo is too complex. It cannot be reasonably placed on 24x24 grid with 2px stroke. My best attempt:
![buy-me-a-coffee-1655137931040](https://user-images.githubusercontent.com/822287/173401730-224bfbe9-268d-4faf-b354-a8b506f7ac5e.gif)

Other coffee icons (showing only few, there are several more combinations):
![icons-1655137852335](https://user-images.githubusercontent.com/822287/173401881-c6c3f905-7fa5-47b4-a9f3-faf325a68da5.gif)

**Comment by psynyde** [comment]
Hello.Firstly I want to say that I'm really impressed by the dedication you've put into this project.This much progress in this short period of time is really amazing.❤

As for the icons i think they all fit the theme well & as impressive as previous ones..& for the `buymeacoffee` logo i think you can follow a simpler approach.you can check `bio.link`'s buymeacoffee logo as reference i think.
Edit:
`Preview:` 
![Screenshot_20220613-234622~2](https://user-images.githubusercontent.com/75927811/173413883-39d2db1d-df9f-4850-b506-203d0ff8047a.png)

**Comment by cyberalien** [comment]
Thanks!

Problem with that logo is there are 4 lines in top part. With 2px width and spacing, it ends up taking 14px. That's more than half of available image space. This can easily be done with 1px wide icons, but this icon set attempts to follow Material Icons guidelines, so it is not an option.

Another attempt. This looks not precise, but I think it might pass for logo:

![buy-me-a-coffee-1655146351994](https://user-images.githubusercontent.com/822287/173424400-9006fec8-1015-4d9a-ab73-86823fc65a7a.gif)

**Comment by cyberalien** [comment]
I've had an interesting idea for animation: fill coffee cup. Applied it to buy me a coffee and beer icons:

![demo-1655208315798](https://user-images.githubusercontent.com/822287/173573352-d6fd682a-3a73-4ac4-97d7-63d23f7111ba.gif)

Also cleaned up buy me a coffee icon.

Article icon is also there, as `text-box`. It is similar to icon in Material Design set, but with animation.

**Comment by cyberalien** [comment]
Experiments continue. Added few sun and moon icons, also icon for switching light/dark modes.

So from requested icons I think only lightbulb icon is currently missing.

**Comment by cyberalien** [comment]
Added last missing icon: lightbulb (and few variations).

Some of recently added icons:
![demo-1657648837993](https://user-images.githubusercontent.com/822287/178561805-51cb86a1-fa35-4cdd-a7d6-7b5f50083715.gif)

If you need any variations of those icons, please post here.
