### ISSUE TITLE
[Icon Request] Moon Rising, Transition between Sun and Moon and Transition icons in general

### ISSUE THREAD

**Issue by anurag-roy** [cyberalien/line-md#3]
Hello! First of all, congrats and thanks for the work on this whole icon set. Using these animated icons honestly feels like cheating, because they do so much with minimal effort on the user end.

Coming straight to the point, here are a few icon requests:
1. Moon Rising: Basically equivalents of the sun-rising icons, with a starting rising animation instead of a line animation
2. Transition between Sun and Moon: Transition animation between sun and moon (would be very helpful as a light and dark theme toggle). Maybe something like this gif 

    ![sun-moon](https://user-images.githubusercontent.com/53750093/191783241-f6317e28-e9b7-4c9d-bd49-dbb301bc3e3b.gif)

These were two specific ones, but overall I'd also request for much more transition icons. These transition icons are so impactful in everyday UI micro-interactions e.g. checked to unchecked or vice versa. They also make the most difference compared to using plain SVGs and have a lot of potential imo. Listing some off the top of my head: 
- Hamburger menu and cross
- Clipboard and copied to clipboard
- Switch toggle on and off
- Play and pause

Sorry to bombard you like this but I really am curious to hear your thoughts.

**Comment by cyberalien** [comment]
Thanks!

1. Easily doable.
2. Might be tricky, but I'll see what can be done.

Other icons: sure.

It might take a while. I'm currently working on urgent stuff that might take a week or so, after that can have some more fun with animations.

**Comment by cyberalien** [comment]
So I've been attempting to transition moon to sun and back, figured out how to do it (click icon and refresh page to see animation):

![test](https://user-images.githubusercontent.com/822287/193221144-78d7c384-151a-437c-82e4-3ee345da5d2c.svg)

So it is definitely doable. A bit hacky because during animation edges of moon become sharp, but I don't think it can be noticed.

**Comment by anurag-roy** [comment]
Looks awesome!

**Comment by cyberalien** [comment]
Transitions for menu done:

![menu-to-close-alt-transition](https://user-images.githubusercontent.com/822287/193315664-47faa98c-640f-4d00-92a5-9677d905e452.svg)
![close-to-menu-alt-transition](https://user-images.githubusercontent.com/822287/193315668-3fc58d8d-0928-4d3d-a7e3-607681550ac4.svg)

Few of new moon/sun transition icons:

![moon-to-sunny-outline-loop-transition](https://user-images.githubusercontent.com/822287/193316153-c64c2a0e-03c9-48e8-9bdb-f54d8d0ff97f.svg)
![sunny-filled-loop-to-moon-alt-filled-loop-transition](https://user-images.githubusercontent.com/822287/193316155-ce7d32ba-279e-4cd8-a83c-d0319ebaaa1c.svg)

Animating moon icon became a bit more complex due to many different variations. I'm not sure which moon animation to keep. Please check this thread tell me which moon animation you prefer: https://github.com/cyberalien/line-md/issues/4

**Comment by cyberalien** [comment]
Added play and pause icons:

![play](https://user-images.githubusercontent.com/822287/195659124-f35eaaf9-4caa-41bc-a3de-055e8b87245a.svg)
![pause](https://user-images.githubusercontent.com/822287/195659189-4034a6a8-fbbf-41b3-97e1-8df7adc10fb1.svg)

and transitions between them:

![pause-to-play-transition](https://user-images.githubusercontent.com/822287/195659392-c2415d72-b8e8-4f1c-9c0f-8412a9949831.svg)
![play-to-pause-transition](https://user-images.githubusercontent.com/822287/195659397-c1f8c8c4-fcac-472e-be14-ed84befcee80.svg)

**Comment by cyberalien** [comment]
Added few switch icons:
![switch-off](https://user-images.githubusercontent.com/822287/196521557-2090f0e6-91c0-474a-9925-e64a8e026034.svg)
![switch-filled](https://user-images.githubusercontent.com/822287/196521617-dcced72f-6903-4d7d-8daa-5d67a8485e75.svg)

with on/off transitions for both normal and filled icons:
![switch-filled-to-switch-off-filled-transition](https://user-images.githubusercontent.com/822287/196521485-cf961528-d58f-4c2e-9ebc-e37733d1c35d.svg)

and clipboard to clipboard-check transitions:
![clipboard-to-clipboard-check-transition](https://user-images.githubusercontent.com/822287/196521833-5062b8fd-a427-4155-a027-20fac46c1cb6.svg)

I think that's it for this issue. Any icons I've missed?

**Comment by anurag-roy** [comment]
I think thats all for now! Thanks so much for all the icons!
